export {
  WORKSPACE_DIRECTORIES,
  canonicalRoot,
  checkWorkspacePath,
  isInsideRoot,
  type PathCheck,
  type PathRejection,
} from "./paths.js";

export {
  DEFAULT_RETRY,
  withLockRetry,
  writeFileAtomic,
  writeFileExclusive,
  type RetryPolicy,
} from "./atomic.js";

export {
  newManifest,
  readManifest,
  serializeManifest,
  type ManifestReport,
  type NewManifestInput,
} from "./manifest.js";

export {
  WorkspaceError,
  checkWorkspaceHealth,
  createWorkspace,
  openWorkspace,
  repairWorkspaceLayout,
  renameWorkspace,
  touchManifest,
  workspaceModifiedAt,
  type CreateWorkspaceInput,
  type HealthReport,
  type OpenWorkspaceInput,
  type WorkspaceErrorKind,
} from "./store.js";

export {
  acquireLock,
  detectSyncFolder,
  fileRecentStore,
  fileTrustStore,
  releaseLock,
  writeJsonFile,
  type LockRecord,
  type LockResult,
  type RecentStore,
  type SessionPaths,
  type TrustRecord,
  type TrustStore,
} from "./session.js";

export { workspaceCommands, type WorkspaceCommandDeps } from "./commands.js";
export { objectCommands, type ObjectCommandDeps } from "./object-commands.js";
export { projectCommands } from "./project-commands.js";
export { threadCommands } from "./thread-commands.js";
export { taskCommands } from "./task-commands.js";
export { protocolCommands } from "./protocol-commands.js";
export { claimCommands } from "./claim-commands.js";
export { bibliographyCommands } from "./bibliography-commands.js";
export { assetCommands, type AssetCommandDeps } from "./asset-commands.js";
export { coeditNoteCommands, type CoeditNoteCommandDeps } from "./coedit-note-commands.js";

export { canonicalJson, prettyJson, sha256, sha256Text } from "./canonical-json.js";

export {
  ASSET_SCHEMA,
  ManagedAssetImportError,
  importManagedAsset,
  missingAssetFiles,
  readManagedAsset,
  type ImportManagedAssetInput,
  type ImportManagedAssetReceipt,
  type ManagedAssetDuplicate,
  type ManagedAssetObject,
} from "./assets.js";

export {
  commitCanonical,
  recoverCanonicalTransactions,
  withCanonicalWrite,
  type CanonicalEvent,
  type CommitCanonicalInput,
  type RecoveryReport,
  type RecoveryAuditInput,
  type TransactionTarget,
} from "./canonical-transaction.js";

export {
  INBOX_SCHEMA,
  COLLECTION_SCHEMA,
  OBJECT_SCHEMA_VERSION,
  RELATION_SCHEMA,
  ANNOTATES_RELATION,
  COMMENTS_ON_RELATION,
  AnnotationValidationError,
  ThreadMessageMissing,
  ThreadMessageNotYours,
  ThreadNotFound,
  ThreadValidationError,
  addThreadReply,
  createThread,
  editThreadMessage,
  listThreads,
  moveThreadAnchor,
  setThreadStatus,
  type EditThreadMessageInput,
  type MoveThreadAnchorInput,
  type ReplyToThreadInput,
  type SetThreadStatusInput,
  type StartThreadInput,
  type StoredThread,
  type ThreadQuery,
  type ThreadWrite,
  type ThreadWriteInput,
  TASK_FOR_RELATION,
  TaskBlockingCycle,
  TaskLinkError,
  TaskNotFound,
  TaskValidationError,
  completeStoredTask,
  createTask,
  linkTask,
  listTasks,
  reopenStoredTask,
  unlinkTask,
  updateTask,
  type CreateTaskInput,
  type LinkTaskInput,
  type StoredTask,
  type TaskQuery,
  type TaskWrite,
  type TaskWriteInput,
  type UpdateTaskInput,
  NoteTargetError,
  FileAttachmentError,
  HAS_FILE_RELATION,
  ObjectHistoryCorruptionError,
  ObjectCaptureContextConflict,
  ObjectNotPromotable,
  ObjectTypeNotCreatable,
  ObjectOrganizationConflict,
  ObjectPublicationValidationError,
  ObjectTrashConflict,
  ObjectTrashCorruptionError,
  ObjectVersionConflict,
  bulkTagObjects,
  changeCollectionMembership,
  annotationsForObject,
  attachFile,
  attachedFiles,
  createAnnotation,
  quotedAnnotationIds,
  sendAnnotationsToNote,
  updateAnnotation,
  detachFile,
  createInboxItem,
  createObject,
  promoteInboxItem,
  canonicalObjectPath,
  createRelation,
  duplicateObject,
  listCanonicalObjects,
  listCanonicalRelations,
  listTrash,
  previewTrashCleanupPolicy,
  previewTrashPurge,
  purgeTrash,
  quickCapture,
  readTrashCleanupPolicy,
  objectActivity,
  objectHistory,
  objectOrganization,
  previewObjectPublication,
  previewObjectRestore,
  previewObjectTrash,
  publishObject,
  readCanonicalObject,
  readObjectVersion,
  relationsForObject,
  restoreObjectVersion,
  restoreTrashedObject,
  setTrashCleanupPolicy,
  trashObject,
  verifyObjectHash,
  type CanonicalIds,
  type AttachFileInput,
  type CreateAnnotationInput,
  type SendAnnotationsReceipt,
  type SendAnnotationsToNoteInput,
  type StoredAnnotation,
  type UpdateAnnotationInput,
  type DetachFileInput,
  type CreateObjectInput,
  type PromoteInboxItemInput,
  type BulkTagChange,
  type BulkTagObjectsInput,
  type BulkTagReceipt,
  type CanonicalObject,
  type CanonicalRelation,
  type ChangeCollectionMembershipInput,
  type CollectionMembershipAction,
  type CollectionMembershipReceipt,
  type CreateInboxItemInput,
  type CreateRelationInput,
  type ObjectHistoryEntry,
  type ObjectOrganizationCollection,
  type ObjectOrganizationSnapshot,
  type ObjectPublicationImpact,
  type ObjectPublicationPreview,
  type ObjectRestorePreview,
  type ObjectTrashEntry,
  type ObjectTrashImpact,
  type ObjectTrashManifest,
  type ObjectTrashRelationGuard,
  type PurgeTrashInput,
  type PurgeTrashReceipt,
  type QuickCaptureContextInput,
  type QuickCaptureInput,
  type QuickCaptureProvenance,
  type QuickCaptureReference,
  type SetTrashCleanupPolicyInput,
  type TrashCleanupPolicy,
  type TrashCleanupPolicyPreview,
  type TrashPurgeEntry,
  type TrashPurgePreview,
  type ObjectVersionGuard,
  type ObjectActivityEntry,
  type PublishObjectInput,
  type DuplicateObjectInput,
  type RestoreTrashedObjectInput,
  type TrashObjectInput,
  type TrashRelationRecord,
  IN_PROJECT_RELATION,
  NotAProjectError,
  ProjectValidationError,
  assignObjectToProject,
  configureProject,
  createProject,
  listProjects,
  projectForObject,
  projectMembers,
  projectSettingsOf,
  type AssignToProjectInput,
  type ConfigureProjectInput,
  type CreateProjectInput,
  type ProjectAssignment,
  type ProjectSummary,
  ProtocolFrozen,
  ProtocolNotFound,
  ProtocolValidationError,
  ensureProtocol,
  freezeStoredProtocol,
  logProtocolDeviation,
  protocolForProject,
  protocolTitle,
  updateProtocol,
  type EnsureProtocolInput,
  type EnsureProtocolResult,
  type LogProtocolDeviationInput,
  type ProtocolChanges,
  type ProtocolWrite,
  type ProtocolWriteInput,
  type StoredProtocol,
  type UpdateProtocolInput,
  CONTRADICTS_RELATION,
  SUPPORTS_RELATION,
  ClaimNotFound,
  ClaimValidationError,
  EvidenceError,
  attachEvidence,
  createClaim,
  detachEvidence,
  listClaims,
  sendEvidenceToClaim,
  updateClaim,
  type AttachEvidenceInput,
  type ClaimEvidence,
  type ClaimQuery,
  type ClaimSummary,
  type ClaimWrite,
  type ClaimWriteInput,
  type CreateClaimInput,
  type DetachEvidenceInput,
  type EvidenceClaimTarget,
  type EvidenceExcerpt,
  type EvidenceWrite,
  type ExistingClaimTarget,
  type NewClaimTarget,
  type SendEvidenceReceipt,
  type SendEvidenceToClaimInput,
  type StoredClaim,
  type UpdateClaimInput,
} from "./objects.js";

export {
  applyStructuredSyncChange,
  type ApplyStructuredChangeInput,
  type ApplyStructuredChangeResult,
} from "./structured-sync.js";

export {
  checkpointCoeditDocument,
  currentCoeditPresence,
  materializeCoeditMarkdown,
  materializedCoeditCharacters,
  mergeCoeditOperations,
  type CoeditCheckpoint,
  type CoeditDeleteOperation,
  type CoeditDocument,
  type CoeditInsertOperation,
  type CoeditOperation,
  type CoeditPresence,
} from "./coedit.js";

export {
  CoeditVersionConflict,
  applyCoeditNoteOperations,
  createCoeditNote,
  listCoeditNotes,
  readCoeditNote,
  replaceCoeditNoteText,
  type ApplyCoeditOperationsInput,
  type CoeditNoteState,
  type CoeditNoteView,
  type CoeditWriteIds,
} from "./coedit-notes.js";

export {
  createExternalDraftConflict,
  listStructuredConflicts,
  resolveStructuredConflict,
  type CreateExternalDraftConflictInput,
  type ResolveStructuredConflictInput,
  type StructuredConflict,
} from "./conflicts.js";
